### ISSUE TITLE
readline 7 revisions needed

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-games#693]
- [x] freeciv

**Comment by tomyun** [comment]
I had a brief look at this issue today after finding out R and some other formulae were broken for me. There are two formulae, `freeciv` and `gnu-go`, depend on `readline`. With inspection with `otool`, however, I couldn't find any dylibs for it and concluded they both statically link against `readline`.

Of course, it'd be still a safe bet to bump revisions anyways.

**Comment by ilovezfs** [comment]
Yes, it's a good idea to check they still build in that case. If you're sure the existing users do not need an upgrade to fix it, then the Homebrew Testing Job can be used on Jenkins instead of a revision to verify the build still works.

**Comment by tomyun** [comment]
I wouldn't bother making revision bumps for them, we have only two, but also be interested in trying Homebrew Testing Job for sure. May I ask how we can trigger tests without pushing new PRs?

**Comment by ilovezfs** [comment]
You put in the parameters
```
--tap=homebrew/games freeciv
```
here https://bot.brew.sh/job/Homebrew%20Testing/

The button you want is "Build with Parameters," which should be visible if you are logged into Jenkins.

**Comment by tomyun** [comment]
This testing feature looks very nice! Thanks.

- [freeciv](https://bot.brew.sh/job/Homebrew%20Testing/1123/) passed
- [gnu-go](https://bot.brew.sh/job/Homebrew%20Testing/1124/) failed (due to audit)

It seems they both run fine without revision bump, but I'll open PR for that anyways, at least to fix audit error. Never know what improvements the new version of readline brings under the hood either.

**Comment by tomyun** [comment]
`freeciv` and `gnu-go` revision bumps pulled.

**Comment by ilovezfs** [comment]
@tomyun cool thank you!
