### ISSUE TITLE
Add Pingus (Lemmings clone)

### ISSUE THREAD

**Issue by chauncey-garrett** [Homebrew/homebrew-games#729]
https://github.com/Pingus/pingus

**Comment by tomyun** [comment]
I gave it a quick shot the other day, but it somehow didn't build right out of the box. Given that the latest version was released almost 5 years ago and there are lots of commits since then, we might need to wait for a new release coming out.

Meanwhile, if you interested in opening a pull request for it yourself, you're more than welcome to do so. Please take a look at [the guide](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) and let us know any questions if you have.

**Comment by kencu** [comment]
I have this working on macports -- perhaps I'll try to make this my first home brew submission... or take a look at my port file and go from there if you want.

**Comment by MikeMcQuaid** [comment]
Passing on this but may accept a PR in homebrew/core.
